# Data analysis1

In [9]:
print(2+2)

4


循环语句：

In [3]:
import numpy as np
import pandas as pd

In [12]:
a = np.array([1,2,3,4])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [15]:
l = [0,1,2,3]
a = np.array(l)
a

array([0, 1, 2, 3])

In [16]:
b = np.array([1,2,3])

In [17]:
b

array([1, 2, 3])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.twos

AttributeError: module 'numpy' has no attribute 'twos'

In [21]:
np.ones(5,dtype = "str")

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [22]:
np.ones(5,dtype = "bool")

array([ True,  True,  True,  True,  True])

In [23]:
a = np.array([1,2,3,4])
a.fill(5)

In [24]:
a

array([5, 5, 5, 5])

In [25]:
a = a.astype("float")
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

In [26]:
a = np.arrange(1,11)
a

AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [29]:
a = np.linspace(1,10,21)
a

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [30]:
np.random.rand(10)

array([0.3389412 , 0.57153206, 0.70770323, 0.29649995, 0.72000596,
       0.03636095, 0.39092042, 0.26083428, 0.16355872, 0.77830813])

In [31]:
np.random.randn(10)

array([-0.06603768,  0.52904791,  0.52853891, -0.02133747, -1.63225831,
        0.22819244, -1.80080915,  0.91783934,  1.68398576, -0.42814294])

In [32]:
np.random.randint(1,10,10)

array([9, 9, 7, 7, 6, 2, 3, 7, 6, 8])

In [33]:
a.size()

TypeError: 'int' object is not callable

In [34]:
a.size

21

In [35]:
a = np.array([0,1,2,3])
a[2]

2

In [36]:
a[0] = 10
a

array([10,  1,  2,  3])

In [37]:
a = np.array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [38]:
a[1:-2]

array([12, 13])

In [3]:
ob = np.array([21000,218800,22240,23450,25000])
i = 0
print("day1的票房为21000")
while i <= 3:
    day = ob[i+1] - ob [i]
    print("day{}的票房为{}".format(i+1,day))
    i += 1
    pass

day1的票房为21000
day1的票房为197800
day2的票房为-196560
day3的票房为1210
day4的票房为1550


In [4]:
ob = np.array([21000,21880,22240,23450,25000])
i = 0
print("day1的票房为21000")
while i <= 3:
    day = ob[i+1] - ob [i]
    print("day{}的票房为{}".format(i+2,day))
    i += 1
    pass


day1的票房为21000
day2的票房为880
day3的票房为360
day4的票房为1210
day5的票房为1550


In [5]:
ob[:-1]

array([21000, 21880, 22240, 23450])

In [6]:
ob[-1]

25000

In [7]:
a = np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [9]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a = np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,45]])
a

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 45]])

In [12]:
a[0,3:5]

array([4, 5])

In [13]:
a[4:,4:]

array([], shape=(0, 1), dtype=int32)

In [14]:
a[2:,3:]

array([[24, 25],
       [34, 45]])

In [15]:
a[:,2]

array([ 3, 13, 23, 33])

In [16]:
a[1:4:2,:]

array([[11, 12, 13, 14, 15],
       [31, 32, 33, 34, 45]])

In [17]:
a= np.array([0,1,2,3,4])
b = a[2:4]
print(b)

[2 3]


In [19]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
index = [1,2,-3]
y = a[index]
print(y)

[10 20 70]


In [21]:
mask = np.array([0,2,2,1,4,2,0,3,2,1],dtype = bool)
mask

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [22]:
a[mask]

array([10, 20, 30, 40, 50, 70, 80, 90])

In [23]:
index = [1,2,-3]
y = a(index)
print(y)

TypeError: 'numpy.ndarray' object is not callable

In [24]:
import pandas as pd
import nmupy as np

ModuleNotFoundError: No module named 'nmupy'

In [25]:
import pandas as pd
import numpy as np

In [29]:
s = pd.Series([1,3,5,np.nan,6,8],index = ['a','b','c','d','f','e'])
print(s)

a    1.0
b    3.0
c    5.0
d    NaN
f    6.0
e    8.0
dtype: float64


In [30]:
s.index

Index(['a', 'b', 'c', 'd', 'f', 'e'], dtype='object')

In [31]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [32]:
s[2]

5.0

In [33]:
s[0]

1.0

In [34]:
s[2:5]

c    5.0
d    NaN
f    6.0
dtype: float64

In [35]:
s[::2]

a    1.0
c    5.0
f    6.0
dtype: float64

In [36]:
s.index.name = '索引'

In [37]:
s

索引
a    1.0
b    3.0
c    5.0
d    NaN
f    6.0
e    8.0
dtype: float64

In [38]:
s.index = list("abcdef")
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
dtype: float64

In [39]:
s['a':'c']

a    1.0
b    3.0
c    5.0
dtype: float64

In [40]:
s[1;3]

SyntaxError: invalid syntax (<ipython-input-40-89ba693be3f3>, line 1)

In [41]:
s[1:3]

b    3.0
c    5.0
dtype: float64

In [42]:
data = pd.data_range('20230205',periods = 6)
print(data)

AttributeError: module 'pandas' has no attribute 'data_range'

In [43]:
data = pd.date_range('20230205',periods = 6)
print(data)

DatetimeIndex(['2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


In [47]:
df = pd.DataFrame(np.random.rand(6,4),index = data,columns = list('ABCD'))
df

A         B         C         D
2023-02-05  0.306889  0.741417  0.220753  0.110492
2023-02-06  0.182971  0.942749  0.855013  0.006465
2023-02-07  0.602936  0.384673  0.969440  0.054853
2023-02-08  0.442320  0.772305  0.950447  0.778577
2023-02-09  0.539677  0.924028  0.059516  0.292032
2023-02-10  0.143632  0.959888  0.363245  0.205689

In [54]:
df2 = pd.DataFrame({'A':1,'B':pd.Timestamp('20230205'),'C':pd.Series(1,index = list(range(4)),dtype=float),'D':np.array([3]*4,dtype=int),'E':pd.Categorical(["test","train","test","train"]),'F':"abc"})
df2.dtypes
df2

A          B    C  D      E    F
0  1 2023-02-05  1.0  3   test  abc
1  1 2023-02-05  1.0  3  train  abc
2  1 2023-02-05  1.0  3   test  abc
3  1 2023-02-05  1.0  3  train  abc

In [50]:
df.head()

A         B         C         D
2023-02-05  0.306889  0.741417  0.220753  0.110492
2023-02-06  0.182971  0.942749  0.855013  0.006465
2023-02-07  0.602936  0.384673  0.969440  0.054853
2023-02-08  0.442320  0.772305  0.950447  0.778577
2023-02-09  0.539677  0.924028  0.059516  0.292032

In [55]:
df

A         B         C         D
2023-02-05  0.306889  0.741417  0.220753  0.110492
2023-02-06  0.182971  0.942749  0.855013  0.006465
2023-02-07  0.602936  0.384673  0.969440  0.054853
2023-02-08  0.442320  0.772305  0.950447  0.778577
2023-02-09  0.539677  0.924028  0.059516  0.292032
2023-02-10  0.143632  0.959888  0.363245  0.205689

In [56]:
df.index

DatetimeIndex(['2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [57]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [58]:
df.values

array([[0.30688891, 0.74141742, 0.22075274, 0.1104917 ],
       [0.18297052, 0.94274882, 0.85501304, 0.00646482],
       [0.60293611, 0.38467313, 0.96943952, 0.05485317],
       [0.44231962, 0.77230526, 0.95044728, 0.77857708],
       [0.53967678, 0.92402849, 0.05951577, 0.29203191],
       [0.14363243, 0.95988843, 0.36324518, 0.20568859]])

In [60]:
df = pd.read_excel(r"C:\Users\15523\Desktop\Data analysis\豆瓣电影数据.xlsx")
df[:5]

名字      投票人数        类型    产地                 上映时间   时长    年代   评分  \
0  肖申克的救赎  692795.0     剧情/犯罪    美国  1994-09-10 00:00:00  142  1994  9.6   
1    控方证人   42995.0  剧情/悬疑/犯罪    美国  1957-12-17 00:00:00  116  1957  9.5   
2   美丽人生   327855.0  剧情/喜剧/爱情   意大利  1997-12-20 00:00:00  116  1997  9.5   
3    阿甘正传  580897.0     剧情/爱情    美国  1994-06-23 00:00:00  142  1994  9.4   
4    霸王别姬  478523.0  剧情/爱情/同性  中国大陆  1993-01-01 00:00:00  171  1993  9.4   

     首映地点  
0  多伦多电影节  
1      美国  
2     意大利  
3   洛杉矶首映  
4      香港

In [62]:
s = pd.Series(np.arange(1,10),index = [['a','a','a','b','b','b','c','c','c'],[1,2,3,1,2,3,1,2,3]])
s

a  1    1
   2    2
   3    3
b  1    4
   2    5
   3    6
c  1    7
   2    8
   3    9
dtype: int32

In [63]:
s.index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [64]:
s['a']

1    1
2    2
3    3
dtype: int32

In [65]:
s["a":'c']

a  1    1
   2    2
   3    3
b  1    4
   2    5
   3    6
c  1    7
   2    8
   3    9
dtype: int32

In [66]:
s[:,1]

a    1
b    4
c    7
dtype: int32

In [67]:
s['b',2]

5

In [68]:
s.unstack()

1  2  3
a  1  2  3
b  4  5  6
c  7  8  9

In [69]:
s.unstack().stack()

a  1    1
   2    2
   3    3
b  1    4
   2    5
   3    6
c  1    7
   2    8
   3    9
dtype: int32

In [4]:
data = pd.DataFrame(np.arange(12).reshape(4,3),index = [['a','a','b','b'],[1,2,1,2]],columns=[['A','A','B'],["first","second","third"]])
data

A            B
    first second third
a 1     0      1     2
  2     3      4     5
b 1     6      7     8
  2     9     10    11

In [79]:
data['B']

third
a 1      2
  2      5
b 1      8
  2     11

In [7]:
data.index.names = ["row1","row2"]
