# 第二次课作业

In [1]:
import numpy as np
import pandas as pd

（1）创建一个1到10的数组，然后逆序输出。

In [54]:
a1 = np.array(range(1,11))
a1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [12]:
a2 = np.ones(20,dtype = 'int')
a2.reshape(4,5).T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [15]:
a3 = np.array(np.random.random(27))
a3.reshape(3,3,3)

array([[[0.31478519, 0.04616391, 0.36960179],
        [0.76267887, 0.10740337, 0.47526344],
        [0.34485692, 0.27650802, 0.03499493]],

       [[0.79439642, 0.87066244, 0.51994693],
        [0.13089496, 0.41965225, 0.43743873],
        [0.41423611, 0.42313168, 0.86572791]],

       [[0.96040151, 0.62413934, 0.64991338],
        [0.35649437, 0.52759015, 0.78500779],
        [0.35458596, 0.30869785, 0.38773171]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [53]:
a4 = np.array(np.random.random(10)*10,dtype = 'float')
index = a4.argsort()
a4 = a4[index]
min = a4[0]
max = a4[9]
a4.min()
a4.max()
a4.sum()
a4.var()

5.408785816009525

（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [63]:
a5 = np.array(np.ceil(np.random.random(10)*10),dtype = 'int')
for value in a5:
    if (value - 1)%2 == 0:
        print("a5的奇数有：{}".format(value))
        print("\n")
        pass
    pass


a5的奇数有：7


a5的奇数有：9


a5的奇数有：7


a5的奇数有：3


a5的奇数有：5


a5的奇数有：3


a5的奇数有：5


a5的奇数有：3




（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [71]:
a6 = np.linspace(0,100,5)
a6.astype(dtype = int)

array([  0,  25,  50,  75, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [76]:
a7 = np.array(np.random.random(10)*10, dtype = 'int')
num = -a7[(a7>3) & (a7<8)]
print("{}的取负为{}".format(a7,num))

[8 9 7 6 1 9 8 5 1 7]的取负为[-7 -6 -5 -7]


（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [88]:
a8 = np.array([1, 2, 3, 4, 5])
np.insert(a8,range(1,5),0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [115]:
a9 = np.array(range(1,26))
a9 = a9.reshape(5,5)

mid = np.copy(a9[1,:])
a9[1,:] = a9[0,:]
a9[0,:] = mid

a9

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

（12）创建一个长度为10的随机向量，并求其累计和。

（13）将数组中的所有奇数替换成-1。

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])